### PR TITLE
ODBC-12 Implement query of all columns for all tables

### PR DESCRIPTION
**Pull request by RussWhitehead**
Currently the connector only returns column metadata for a given named table.
Add the support to query column metadata for all tables

Signed-off-by: William Whitehead <william.whitehead@lexisnexis.com>

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@rpastrana Please review

**Comment by RussWhitehead** [comment]
@richardkchapman Please merge and close

**Comment by richardkchapman** [comment]
Has @rpastrana reviewed it?

**Comment by RussWhitehead** [comment]
Ye he did and I implemented all his comments. THey were lost on my rebase

**Pull request merged**
