### PR TITLE
ODBC-1 Implement the ODBC Connector

### PR DESCRIPTION
**Pull request by RussWhitehead**
Initial check-in of HPCC-ODBC connector, which will allow ODBC compliant applications
to query HPCC datasets and execute HPCC stored procedures/deployed queries. This
check-in will not build yet, as it is dependent on the Progress Software Data Direct
OpenAccess ODBC Client and Server SDK, the HPCC WS_SQL project and the HPCC libraries.

Signed-off-by: William Whitehead <william.whitehead@lexisnexis.com>

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@xwang2713 Please review Jenkins build process
@JamesDeFabia Please review HPCC-ODBC\progress\readme.txt

**Comment by JamesDeFabia** [comment]
Readme.txt looks good to merge

**Comment by richardkchapman** [comment]
Is this for 5.2, and if so should it be targetting a different branch?

**Comment by RussWhitehead** [comment]
This is in its own repository, not tied to any HPCC release

**Pull request merged**
