### PR TITLE
ODBC-21 32 and 64 bit connectors cannot be jointly installed

### PR DESCRIPTION
**Pull request by RussWhitehead**
If either version of the HPCC-ODBC Connector is installed, then
attempts to install the other one results in a popup stating that it
is already installed. This pull request updates the GUID for the 64 bit
version to a unique value, and corrects a product name collision with
the 32 bit version

Signed-off-by: William Whitehead <william.whitehead@lexisnexis.com>

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@rpastrana Please review

**Comment by RussWhitehead** [comment]
@rpastrana Please review new naming conventions

**Comment by rpastrana** [comment]
reviewed.

**Comment by RussWhitehead** [comment]
@richardkchapman This is ready to be merged and closed

**Comment by RussWhitehead** [comment]
@ghalliday Please merge and close this Jida

**Comment by ghalliday** [comment]
Should this be targeting 5.2 (a bit late), or is master fine?

**Comment by RussWhitehead** [comment]
Master is fine, they are not tied to one another

**Pull request merged**
