### PR TITLE
ODBC-18 Add support for DB Catalog

### PR DESCRIPTION
**Pull request by RussWhitehead**
Using the 64bit ODBC driver and connecting with Excel and Access,
it is required for this driver to implement the DAMOBJ_TYPE_CATALOG
case in the OAIP_Schama callback. We shall report the catalog name
as "HPCC Systems" in this scenario

Signed-off-by: William Whitehead <william.whitehead@lexisnexis.com>

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@rpastrana please review

**Comment by RussWhitehead** [comment]
@richardkchapman Please merge and close

**Comment by richardkchapman** [comment]
Has Rodrigo reviewed it?

**Comment by RussWhitehead** [comment]
Yes he did and I integrated his suggestions
@rpastrana

**Pull request merged**
